/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SubtaskService } from "../subtask.service";
import { SubtaskCreateInput } from "./SubtaskCreateInput";
import { Subtask } from "./Subtask";
import { SubtaskFindManyArgs } from "./SubtaskFindManyArgs";
import { SubtaskWhereUniqueInput } from "./SubtaskWhereUniqueInput";
import { SubtaskUpdateInput } from "./SubtaskUpdateInput";

export class SubtaskControllerBase {
  constructor(protected readonly service: SubtaskService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Subtask })
  async createSubtask(
    @common.Body() data: SubtaskCreateInput
  ): Promise<Subtask> {
    return await this.service.createSubtask({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Subtask] })
  @ApiNestedQuery(SubtaskFindManyArgs)
  async subtasks(@common.Req() request: Request): Promise<Subtask[]> {
    const args = plainToClass(SubtaskFindManyArgs, request.query);
    return this.service.subtasks({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Subtask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async subtask(
    @common.Param() params: SubtaskWhereUniqueInput
  ): Promise<Subtask | null> {
    const result = await this.service.subtask({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Subtask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSubtask(
    @common.Param() params: SubtaskWhereUniqueInput,
    @common.Body() data: SubtaskUpdateInput
  ): Promise<Subtask | null> {
    try {
      return await this.service.updateSubtask({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Subtask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSubtask(
    @common.Param() params: SubtaskWhereUniqueInput
  ): Promise<Subtask | null> {
    try {
      return await this.service.deleteSubtask({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
